<a href="https://colab.research.google.com/github/NastasiaMazur/VU_1_1/blob/main/exercises/HomeExercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Home Exercise 3: Creating Neural Model in PyTorch

In this home exercise, you will first learn how to create a neural model in PyTorch and then you will train and improve a mini-implementation of an embedding model.


---

## **Exercise 3a: Neural Network Model**

First we need to import the neural network module of PyTorch:

In [84]:
import torch
import torch.nn as nn

We can use `nn.Linear(H_in, H_out)` to create a a linear layer. This will take a matrix of `(N, *, H_in)` dimensions and output a matrix of `(N, *, H_out)`. The `*` denotes that there could be arbitrary number of dimensions in between. The linear layer performs the operation `Ax+b`, where `A` and `b` are initialized randomly. If we don't want the linear layer to learn the bias parameters, we can initialize our layer with `bias=False`.

In [85]:
# Create the inputs
input = torch.ones(2,3,4)
print("Input ", input)

# N* H_in -> N*H_out
linear = nn.Linear(4, 2)
linear_output = linear(input)
linear_output

Input  tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


tensor([[[-0.0176,  0.3654],
         [-0.0176,  0.3654],
         [-0.0176,  0.3654]],

        [[-0.0176,  0.3654],
         [-0.0176,  0.3654],
         [-0.0176,  0.3654]]], grad_fn=<ViewBackward0>)

In [86]:
list(linear.parameters()) # Ax + b

[Parameter containing:
 tensor([[-0.4753,  0.4576, -0.1313,  0.4969],
         [ 0.0978,  0.3345, -0.0681,  0.1483]], requires_grad=True),
 Parameter containing:
 tensor([-0.3656, -0.1471], requires_grad=True)]

Let's add an activation function:

In [87]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[0.4956, 0.5903],
         [0.4956, 0.5903],
         [0.4956, 0.5903]],

        [[0.4956, 0.5903],
         [0.4956, 0.5903],
         [0.4956, 0.5903]]], grad_fn=<SigmoidBackward0>)

Instead of creating intermediate layers and passing variables around, we can create a sequence:

In [88]:
block = nn.Sequential(
    nn.Linear(4, 2),
    nn.Sigmoid()
)

input = torch.ones(2,3,4)
output = block(input)
output

tensor([[[0.2633, 0.8530],
         [0.2633, 0.8530],
         [0.2633, 0.8530]],

        [[0.2633, 0.8530],
         [0.2633, 0.8530],
         [0.2633, 0.8530]]], grad_fn=<SigmoidBackward0>)

---

## **Exercise 3b: Word Embeddings**


Instead of using predefined modules of nn we can define our own modules and build custom neural networks. As a toy example, we will convert words to word embeddings. The preprocessing below should be done more elegantly and not as simply as below.

In [89]:
import string

# We will use Shakespeare Sonnet 2
test_sentence = """When forty winters shall besiege thy brow,
And dig deep trenches in thy beauty's field,
Thy youth's proud livery so gazed on now,
Will be a totter'd weed of small worth held:
Then being asked, where all thy beauty lies,
Where all the treasure of thy lusty days;
To say, within thine own deep sunken eyes,
Were an all-eating shame, and thriftless praise.
How much more praise deserv'd thy beauty's use,
If thou couldst answer 'This fair child of mine
Shall sum my count, and make my old excuse,'
Proving his beauty by succession thine!
This were to be new made when thou art old,
And see thy blood warm when thou feel'st it cold."""

training_sentence = test_sentence.translate(str.maketrans('', '', string.punctuation)).lower().split()
print(training_sentence)

['when', 'forty', 'winters', 'shall', 'besiege', 'thy', 'brow', 'and', 'dig', 'deep', 'trenches', 'in', 'thy', 'beautys', 'field', 'thy', 'youths', 'proud', 'livery', 'so', 'gazed', 'on', 'now', 'will', 'be', 'a', 'totterd', 'weed', 'of', 'small', 'worth', 'held', 'then', 'being', 'asked', 'where', 'all', 'thy', 'beauty', 'lies', 'where', 'all', 'the', 'treasure', 'of', 'thy', 'lusty', 'days', 'to', 'say', 'within', 'thine', 'own', 'deep', 'sunken', 'eyes', 'were', 'an', 'alleating', 'shame', 'and', 'thriftless', 'praise', 'how', 'much', 'more', 'praise', 'deservd', 'thy', 'beautys', 'use', 'if', 'thou', 'couldst', 'answer', 'this', 'fair', 'child', 'of', 'mine', 'shall', 'sum', 'my', 'count', 'and', 'make', 'my', 'old', 'excuse', 'proving', 'his', 'beauty', 'by', 'succession', 'thine', 'this', 'were', 'to', 'be', 'new', 'made', 'when', 'thou', 'art', 'old', 'and', 'see', 'thy', 'blood', 'warm', 'when', 'thou', 'feelst', 'it', 'cold']


Next let's find our vocabulary, i.e., all the unique words in the training data:

In [90]:
vocabulary = set(w for w in training_sentence)
vocabulary

{'a',
 'all',
 'alleating',
 'an',
 'and',
 'answer',
 'art',
 'asked',
 'be',
 'beauty',
 'beautys',
 'being',
 'besiege',
 'blood',
 'brow',
 'by',
 'child',
 'cold',
 'couldst',
 'count',
 'days',
 'deep',
 'deservd',
 'dig',
 'excuse',
 'eyes',
 'fair',
 'feelst',
 'field',
 'forty',
 'gazed',
 'held',
 'his',
 'how',
 'if',
 'in',
 'it',
 'lies',
 'livery',
 'lusty',
 'made',
 'make',
 'mine',
 'more',
 'much',
 'my',
 'new',
 'now',
 'of',
 'old',
 'on',
 'own',
 'praise',
 'proud',
 'proving',
 'say',
 'see',
 'shall',
 'shame',
 'small',
 'so',
 'succession',
 'sum',
 'sunken',
 'the',
 'then',
 'thine',
 'this',
 'thou',
 'thriftless',
 'thy',
 'to',
 'totterd',
 'treasure',
 'trenches',
 'use',
 'warm',
 'weed',
 'were',
 'when',
 'where',
 'will',
 'winters',
 'within',
 'worth',
 'youths'}

We introduce a special token, `<unk>`, to tackle the words that are out of vocabulary. We could pick another string for our unknown token if we wanted. The only requirement here is that our token should be unique: we should only be using this token for unknown words. We will also add this special token to our vocabulary.

In [91]:
vocabulary.add("<unk>")

Now we will create the index for our vocabulary - one index to word and one word to index to make looking up words easier:

In [92]:
ix_to_word = sorted(list(vocabulary))
word_to_ix = {word: ind for ind, word in enumerate(ix_to_word)}
word_to_ix

{'<unk>': 0,
 'a': 1,
 'all': 2,
 'alleating': 3,
 'an': 4,
 'and': 5,
 'answer': 6,
 'art': 7,
 'asked': 8,
 'be': 9,
 'beauty': 10,
 'beautys': 11,
 'being': 12,
 'besiege': 13,
 'blood': 14,
 'brow': 15,
 'by': 16,
 'child': 17,
 'cold': 18,
 'couldst': 19,
 'count': 20,
 'days': 21,
 'deep': 22,
 'deservd': 23,
 'dig': 24,
 'excuse': 25,
 'eyes': 26,
 'fair': 27,
 'feelst': 28,
 'field': 29,
 'forty': 30,
 'gazed': 31,
 'held': 32,
 'his': 33,
 'how': 34,
 'if': 35,
 'in': 36,
 'it': 37,
 'lies': 38,
 'livery': 39,
 'lusty': 40,
 'made': 41,
 'make': 42,
 'mine': 43,
 'more': 44,
 'much': 45,
 'my': 46,
 'new': 47,
 'now': 48,
 'of': 49,
 'old': 50,
 'on': 51,
 'own': 52,
 'praise': 53,
 'proud': 54,
 'proving': 55,
 'say': 56,
 'see': 57,
 'shall': 58,
 'shame': 59,
 'small': 60,
 'so': 61,
 'succession': 62,
 'sum': 63,
 'sunken': 64,
 'the': 65,
 'then': 66,
 'thine': 67,
 'this': 68,
 'thou': 69,
 'thriftless': 70,
 'thy': 71,
 'to': 72,
 'totterd': 73,
 'treasure': 74,
 'trenc

👋 ⚒ How can we now lookup which word is the fifth word in our index list?

In [93]:
# Your code here
fifth_ix = 4
fifth_word = [word for word, ix in word_to_ix.items() if ix == fifth_ix][0]
fifth_word
# I considered the 0 index as an OOV word


'an'

We will use a very simple solution of building trigrams to train our model.

In [110]:
trigrams = [([training_sentence[i], training_sentence[i + 1]], training_sentence[i + 2])
            for i in range(len(training_sentence)-2)]
print(trigrams)

[(['when', 'forty'], 'winters'), (['forty', 'winters'], 'shall'), (['winters', 'shall'], 'besiege'), (['shall', 'besiege'], 'thy'), (['besiege', 'thy'], 'brow'), (['thy', 'brow'], 'and'), (['brow', 'and'], 'dig'), (['and', 'dig'], 'deep'), (['dig', 'deep'], 'trenches'), (['deep', 'trenches'], 'in'), (['trenches', 'in'], 'thy'), (['in', 'thy'], 'beautys'), (['thy', 'beautys'], 'field'), (['beautys', 'field'], 'thy'), (['field', 'thy'], 'youths'), (['thy', 'youths'], 'proud'), (['youths', 'proud'], 'livery'), (['proud', 'livery'], 'so'), (['livery', 'so'], 'gazed'), (['so', 'gazed'], 'on'), (['gazed', 'on'], 'now'), (['on', 'now'], 'will'), (['now', 'will'], 'be'), (['will', 'be'], 'a'), (['be', 'a'], 'totterd'), (['a', 'totterd'], 'weed'), (['totterd', 'weed'], 'of'), (['weed', 'of'], 'small'), (['of', 'small'], 'worth'), (['small', 'worth'], 'held'), (['worth', 'held'], 'then'), (['held', 'then'], 'being'), (['then', 'being'], 'asked'), (['being', 'asked'], 'where'), (['asked', 'where'

In [111]:
class NGramLanguageModeler(nn.Module):

    def __init__(self, vocab_size, embedding_dim, window_size, hidden_dim):
        super(NGramLanguageModeler, self).__init__()          # calls the constructor of the parent class (nn.Module) to initialize the model

        self.embeddings = nn.Embedding(vocab_size, embedding_dim) # creates an embedding layer;  converts input indices into dense vectors
        self.hidden_layer = nn.Sequential(                        # hidden layer of the model as a sequential container
            nn.Linear(window_size * embedding_dim, hidden_dim),
            nn.ReLU()
        )
        self.output_layer = nn.Linear(hidden_dim, vocab_size)     # creates the output layer; takes the hidden representation and produces output scores for each word in the vocabulary

    def forward(self, inputs):                            # specifies how the input data should be processed through the layers to produce the output
        embeds = self.embeddings(inputs).view((1, -1))    # takes the input indices inputs, passes them through the embedding layer, and flattens the resulting tensor into a 1D tensor
        layer1 = self.hidden_layer(embeds)                # passes the flattened embeddings through the hidden layer, applying the linear transformation followed by the ReLU activation
        output = self.output_layer(layer1)                # passes the result of the hidden layer through the output layer, producing the final output scores for each word in the vocabulary
        probabilities = nn.functional.log_softmax(output, dim=1)
        return probabilities

👋 ⚒ Now let's train the model. Try to adapt the hyperparamters so that the total_loss is reduced. These include in the initial settings:

*   Dimensionality of the embeddings: 10
*   Dimensionality of the hidden layer: 128
*   Number of epochs: 10
*   Learning rate: 0.002
*   Loss function (`NLLLoss()` Negative Log Likelihood right now)

The window size can in this toy example not be changed, since we train on trigrams (so we only have two context words in the set).

The code cell before, the `class NGramLanguageModeler(nn.Module)` defines the exact setup of the network. For the setup one thing to change could be the  activation functions (ReLU and Log-Softmax right now) - others can be found [here](https://pytorch.org/docs/stable/nn.html) for sequential layers and here for other uses as [nn.functional](https://pytorch.org/docs/stable/nn.functional.html)).

Just for comparison, this is the initial output with the first settings of the notebook:

`See how loss decreases with each epoch:  [4.502952638980561, 4.453238930322428, 4.404419487556525, 4.356399970771992, 4.309086953644204, 4.262444785210938, 4.216389432417608, 4.170906921403598, 4.125928629816106, 4.081349758975274]
Loss of the last epoch: 4.081349758975274`




In [125]:
window_size = 2
#embedding_dim = 10
embedding_dim = 50
#hidden_dim = 128
hidden_dim = 256
num_epochs = 10

losses = []
# Negative log likelihood
loss_function = nn.NLLLoss()
ngram_model = NGramLanguageModeler(len(vocabulary), embedding_dim, window_size, hidden_dim)

# What do SGD and lr mean? What happenes if you change them?
optimizer = torch.optim.SGD(ngram_model.parameters(), lr=0.002)

for epoch in range(num_epochs):
    total_loss = 0
    for context, target in trigrams:
        # Step 1. Prepare the inputs to be passed to the model (i.e, turn the words
        # into integer indices and wrap them in tensors)
        context_idxs = torch.tensor([word_to_ix[w] for w in context], dtype=torch.long)

        # Step 2. Recall that torch *accumulates* gradients. Before passing in a
        # new instance, you need to zero out the gradients from the old
        # instance
        optimizer.zero_grad()

        # Step 3. Run the forward pass, getting probabilities over next
        # words - the size of this tensor is 87 corresponding to the size of the vocabulary
        probabilities = ngram_model.forward(context_idxs)

        # Step 4. Compute your loss function. The target word (gold standard label) needs to be
        # wrapped in a tensor.
        loss = loss_function(probabilities, torch.tensor([word_to_ix[target]], dtype=torch.long))

        # Step 5. Do the backward pass and update the gradient
        loss.backward()
        optimizer.step()

        # Get the Python number from a 1-element Tensor by calling tensor.item()
        total_loss += loss.item()
    losses.append(total_loss / len(trigrams))

print("See how loss decreases with each epoch: ", losses)
print("Loss of the last epoch:", losses[-1])

See how loss decreases with each epoch:  [4.513900282108678, 4.4070562240296765, 4.302478693227853, 4.199723203625299, 4.098384302274316, 3.998308734556215, 3.899399879759392, 3.8013143729319614, 3.7038797720343664, 3.60684126140797]
Loss of the last epoch: 3.60684126140797


👋 ⚒ Implement the cosine simmilarity for the trained embeddings. For this you need to choose too find the index of the two words you wish to compare, get their embeddings, convert them into numpy arrays, and run them through the cosine function provided.

In [135]:
import torch

word1 = "beauty"
word2 = "treasure"

index_word1 = word_to_ix[word1]
index_word2 = word_to_ix[word2]
print(index_word1)
print(index_word2)


# Tensor to look up specific embeddings
lookup_tensor = torch.tensor(list(word_to_ix.values()), dtype=torch.long)

# Embedding for the first word in the vocabulary
lookup_embeds = ngram_model.embeddings(lookup_tensor)[0]
#print(lookup_embeds)

# Embedding for the 10th (beauty) word in the vocabulary:
lookup_embeds_beauty = ngram_model.embeddings(lookup_tensor)[10]
print(f"Embedding for word beauty:\n {lookup_embeds_beauty}\n")

# Embedding for the 74th (treasure) word in the vocabulary:
lookup_embeds_treasure = ngram_model.embeddings(lookup_tensor)[74]
print(f"Embedding for word treasure:\n {lookup_embeds_treasure}\n")

#DONE#

# Convert the embedding tensor to a NumPy array:
embedding_array_beauty = lookup_embeds_beauty.detach().numpy()
print(f"Embedding for word beauty as NumPy array:\n {embedding_array_beauty}\n")

embedding_array_treasure = lookup_embeds_treasure.detach().numpy()
print(f"Embedding for word beauty as NumPy array:\n {embedding_array_treasure}\n")

print("__________________________________")






#Convert embeddings into numpy arrays: #my code
embed_word1 = lookup_embeds[0].detach().numpy()
embed_word2 = lookup_embeds[1].detach().numpy()

#from Tuturial_4
# tensor -> np
# new_arr = data.numpy()
# print("This is a np.ndarray", new_arr)
# Convert the embedding tensor to a NumPy array:
embedding_array_beauty = lookup_embeds.detach().numpy()
print(f"Embedding for word beauty as NumPy array: {embedding_array_beauty}")

# Calculate dot product #my code
dot_product = np.dot(embed_word1, embed_word2)
# Calculate norms #my code
norm_word1 = np.sqrt(np.sum(embed_word1**2))
norm_word2 = np.sqrt(np.sum(embed_word2**2))

# Calculate cosine similarity #my code
cosine_similarity = dot_product / (norm_word1 * norm_word2)
print(cosine_similarity)


#cosine_similarity = np.dot(embed_word1, embed_word2) / (np.linalg.norm(embed_word1) * np.linalg.norm(embed_word2))
#print(f"Cosine Similarity between '{word1}' and '{word2}': {cosine_similarity}")

#cosine = np.dot(A,B)/(norm(A, axis=1)*norm(B))

10
74
Embedding for word beauty:
 tensor([ 0.1874, -1.5911, -1.1983, -0.0637, -0.8898, -0.3216,  0.3146, -0.8199,
         0.8877,  0.4137,  1.8490, -1.1068, -0.9410, -0.1924, -0.9412, -2.2147,
        -0.1854,  2.0511,  1.1411,  0.6002,  1.0263,  0.2182, -1.3969,  0.0372,
        -0.5945,  1.0522,  1.7216,  1.4686, -0.5622, -0.9304, -0.9750,  0.6455,
         1.6958, -0.6892,  0.2471,  0.8604, -1.0489, -0.4437, -0.4642, -0.4603,
         1.3571,  0.0344,  0.9118,  0.2122, -0.5425, -0.3866, -0.0241, -2.1106,
         1.1199, -0.3270], grad_fn=<SelectBackward0>)

Embedding for word treasure:
 tensor([-0.3188,  0.9121, -1.0547, -0.8266,  0.7518, -0.1784,  0.6838, -1.2330,
         1.5701,  0.8038, -1.7953,  0.0817, -0.6384, -0.7448,  0.6186, -0.3541,
        -0.1171,  0.3218, -0.7654, -0.4515,  0.4925, -0.9061,  0.2776,  0.4283,
        -0.2674, -0.1220, -0.3852,  2.8406, -0.3106, -0.7495, -0.3628,  0.9984,
        -1.2039,  1.5485,  0.6603,  0.1965,  0.0925, -0.7575,  0.7157, -2.5280,
 

In [ ]:
# Tensor to look up specific embeddings
lookup_tensor = torch.tensor(list(word_to_ix.values()), dtype=torch.long)

# Embedding for the first word in the vocabulary
lookup_embeds = ngram_model.embeddings(lookup_tensor)[0]
print(lookup_embeds)
#cosine = np.dot(A,B)/(norm(A, axis=1)*norm(B))